// import 'linear';
// import 'iris';
// import 'breastCancer';
// import 'reader';
// import 'handwriting';
// import 'fashion';
// import 'toxicity';
// import 'mobilenet';
// import 'linear-json';
// import 'RockPaperScissors';
import 'LizardSpock';
